### ISSUE TITLE
stqism.fodt is unreadable

### ISSUE THREAD

**Issue by stal888** [zetok/stqism#1]
I tried opening that file but all I saw was inane XML tags.

**Comment by zetok** [comment]
Have you tried doing it according to instructions in README.md ?

**Comment by zetok** [comment]
I've just checked, and both LibreOffice 4.3.5.2.0+ on Gentoo and 3.5.4.2 on Debian 7 were able to open that file successfully according to instructions in README.md.

That being said, I realize that it's not as straightforward process as it should be. Perhaps you have any suggestions how it could be done in more user-friendly way?

**Comment by stal888** [comment]
I get this when I open it.
![](https://cloud.githubusercontent.com/assets/774591/6948680/34adc4c2-d864-11e4-98fc-896ca7cbbb6b.png)

**Comment by zetok** [comment]
That's not LibreOffice. If you could, please try again after installing it.
https://www.libreoffice.org/download/libreoffice-fresh/

**Comment by theCoolkal** [comment]
I think it would be easier to use a different format than OpenDocument.

Markdown is easy to use and is plaintext, which is accessible to everyone with a text editor.  Even the GitHub website has a text editor.

**Comment by zetok** [comment]
@theCoolkal that's an unrelated issue;

I have spent time thinking whether markdown could be used, but it simply doesn't provide easy to use WYSIWYG editor with feature set comparable, or even close to those provided by LibreOffice. If you disagree with that, please open new issue for it, listing all *libre* software that is equal or better than LibreOffice when it comes to WYSIWYG editing, and saves in markdown format.

**Comment by zetok** [comment]
Closing, since PEBKAC.

If you have a good reason to believe that it's not the case, please comment for reopen.
