### ISSUE TITLE
Maliciously spreading false information

### ISSUE THREAD

**Issue by typical-shitlord** [zetok/stqism#2]
Why are you spreading FUD that I am stqism?

You've gone ahead and provided zero proof showing so and have gone ahead and added my IRC name to your list.

This is outright libel and if this matter isn't corrected I will be forced to take appropriate action.

**Comment by typical-shitlord** [comment]
![screen shot 2015-04-20 at 3 48 52 am](https://cloud.githubusercontent.com/assets/11949584/7228649/353748ae-e710-11e4-949c-6cb35ff8c544.png)

I have attached a screenshot of my earlier text incase you attempt to edit my text and lie about that too.

**Comment by zetok** [comment]
If you want, I can provide publicly logs from ``#tox-ontopic``.

**Comment by zetok** [comment]
Closing, since it's a troll issue.

If you feel that issue wasn't addressed, feel free to comment for reopen.
